-- Baseline schema, sourced from a pg_dump of the fully-migrated database
-- (2026-07-06). This is a real migration, not a defensive one: no
-- IF NOT EXISTS, no guards. It only ever runs against a genuinely blank
-- database (fresh Testcontainers, a wiped local/prod db) and fails loudly
-- if the schema already exists — that's the point.
--
-- app_group is deliberately not recreated: nothing in the codebase reads or
-- writes it, a relic of an earlier Group-table idea abandoned in favor of a
-- bare group_id number.

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    group_id      BIGINT
);

-- Source of fresh household ids. Not a table — group_id is a plain shared
-- number, not a foreign key (see recipe.owner_id below for why recipe
-- itself no longer carries one).
CREATE SEQUENCE group_id_seq START WITH 1;

-- One active invite link per household; regenerating replaces the token.
CREATE TABLE group_invite (
    group_id BIGINT PRIMARY KEY,
    token    VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE recipe (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     VARCHAR(255),
    token     VARCHAR(5) NOT NULL UNIQUE,
    is_global BOOLEAN NOT NULL DEFAULT false,
    owner_id  BIGINT REFERENCES app_user (id),
    CONSTRAINT recipe_global_or_owner_chk CHECK (is_global OR owner_id IS NOT NULL)
);

CREATE TABLE recipe_ingredient (
    recipe_id  INTEGER REFERENCES recipe (id),
    "position" INTEGER,
    name       VARCHAR(255),
    quantity   VARCHAR(255),
    display    VARCHAR(255),
    type       VARCHAR(255)
);

CREATE TABLE recipe_method_step (
    recipe_id  INTEGER REFERENCES recipe (id),
    "position" INTEGER,
    step       VARCHAR(255)
);
