-- Source of fresh household ids. Not a table — group_id is a plain shared
-- number, not a foreign key (see recipe.group_id below for why).
CREATE SEQUENCE group_id_seq START 1;

-- Auth: households and their members.
CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    group_id      BIGINT NOT NULL
);

-- Retired public-contribution feature — no real user submissions to preserve.
DELETE FROM recipe WHERE source = 'SUBMITTED';

-- New ownership model: a recipe is either global (visible to everyone) or
-- belongs to exactly one household's group_id. No group table — group_id is
-- just a number shared with whichever app_user rows belong to that household.
ALTER TABLE recipe ADD COLUMN token VARCHAR(5);
ALTER TABLE recipe ADD COLUMN is_global BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE recipe ADD COLUMN group_id BIGINT;

-- Everything left over was the curated "House" set — make it global and give
-- each row a token now that every recipe is routed by token, not slug.
UPDATE recipe
SET is_global = true,
    token = substr(md5(random()::text || id::text), 1, 5)
WHERE source = 'HOUSE' OR source IS NULL;

-- Now that every row has a token, tighten the constraints the app relies on.
ALTER TABLE recipe ALTER COLUMN token SET NOT NULL;
ALTER TABLE recipe ADD CONSTRAINT recipe_token_unique UNIQUE (token);
ALTER TABLE recipe ADD CONSTRAINT recipe_global_or_group_chk CHECK (is_global OR group_id IS NOT NULL);

-- Old columns from the pre-auth schema, fully superseded above.
ALTER TABLE recipe DROP COLUMN slug;
ALTER TABLE recipe DROP COLUMN source;
